### PR TITLE
feature: add `npm` option to allow usage of 'filter-by-workspace-path-plugin' without npm

### PR DESCRIPTION
**Pull request by Maxim-Durand**
Fixes https://github.com/restfulhead/npm-auto-plugins/issues/16

Added "non_npm" usage for the plugin (updated doc too).

### CODE REVIEW

**Comment by Maxim-Durand** [comment]
@restfulhead What do you think ?

**Comment by restfulhead** [comment]
@Maxim-Durand I think it's a great idea. Thanks for the contribution. I will review soon.

**Comment by restfulhead** [comment]
@Maxim-Durand Sorry for the delay. I have a small suggestion: Instead of an option `non_npm`, how about we add an option `with_npm` or just `npm` that defaults to `true`? It gives us flexibility to perhaps add other package managers in future. If you agree, could you make the change? Happy to merge afterwards.

**Comment by Maxim-Durand** [comment]
@restfulhead I made your recommended changes and updated the `README.md` so it will be easy to add new config params.
I also ran the lint and tests successfully.

**Comment by restfulhead** [comment]
LGTM, thank you! Going to merge and release.

**Pull request merged**
